
(let ((continue t))
  ;; install missing packages given from variable package-selected-packages (see documentation)
  (when (cl-remove-if 'package-installed-p package-selected-packages)
    (package-refresh-contents)
    (setf continue (package-install-selected-packages)))

  (when continue
    (require 'company)
    (require 'ivy)
    (require 'smooth-scrolling)
    (require 'yasnippet)
    (require 'yo-mode-line)
    (require 'electric)
    (electric-pair-mode 1)
    (electric-indent-mode)
    (global-company-mode)
    (ivy-mode 1)
    (show-paren-mode)
    (smooth-scrolling-mode)
    (set-language-environment "UTF-8")
    (set-default-coding-systems 'utf-8)
    (fringe-mode 20)
    (yo-update-mode-line)
    (yas-global-mode 1)
    (blink-cursor-mode -1)))
